spring.datasource.url=jdbc:mysql://localhost:3306/application
spring.datasource.username=root
spring.datasource.password=rootpass
spring.jpa.hibernate.ddl-auto=update 
#essa última linha serve para gerar as alterações no banco de dados

spring.mvc.view.prefix=/WEB-INF/
spring.mvc.view.suffix=.jsp