spring.datasource.url=jdbc:mysql://localhost:3306/application 
#Define a URL de conexão JDBC para o banco de dados MySQL chamado application, rodando localmente na porta 3306.

spring.datasource.username=root
spring.datasource.password=rootpass
#usuário e senha do banco

spring.jpa.hibernate.ddl-auto=update 
#Configura o Hibernate para atualizar automaticamente o esquema do banco de dados conforme as mudanças nas entidades

spring.mvc.view.prefix=/WEB-INF/
#Define o prefixo do caminho das páginas JSP. As páginas JSP devem estar dentro da pasta /WEB-INF/

spring.mvc.view.suffix=.jsp
#Define que todas as páginas de visualização têm a extensão .jsp